<a href="https://colab.research.google.com/github/Akansha009/DataScience/blob/main/Project_2_Classification_of_Customers_using_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import numpy as np
import pandas as pd

In [66]:
#Step 1 :Gathering the Data
data=pd.read_csv("/content/Social_Network_Ads.csv")
print(data)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [67]:
data=data.drop(['User ID'],axis=1)#removing unwanted column
print(data)

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]


In [68]:
#Step 2 :Data Cleaning-
data["Gender"]=data['Gender'].apply({'Male':1,'Female':0}.get)
print(data)

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]


In [69]:
#Step 3 :Dividing data into Independant and Depandant Variables-
x=data[['Gender','Age','Purchased']]
y=data['EstimatedSalary']


In [70]:
#Step 4 :splitting data into training and testing set-
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.75)

In [71]:
#Step 5 : Creating a ML model using KNN algorithm
#import KNN algorithm
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)
print(y_pred)


[ 15000  20000  72000  47000  34000  80000  20000  71000  80000  30000
  50000  70000  50000  50000  70000  43000  47000  41000  21000  26000
  50000  80000  50000  72000  26000  35000  31000  70000  47000  89000
  54000  43000  52000  26000  72000  89000  73000  33000 144000 134000
  25000  36000  28000  33000 144000  22000  57000  42000  21000  47000
  47000  20000  23000  28000  42000  20000  15000  60000  41000  15000
  54000  21000  15000  22000  55000  33000  20000  82000  49000  20000
  30000  57000  28000  80000  54000  52000  42000  83000  47000  21000
  34000  52000  21000  48000  47000  72000  42000  42000  15000  23000
  43000  23000  45000  57000  22000  23000  52000  89000  42000  35000]


In [72]:
#Calculating the accuracy of the ML model-
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
print("The confusion matrix of the ML model using KNN algorithm is",cm)
print("The accuracy of the ML model using KNN algorithm is",ac)

The confusion matrix of the ML model using KNN algorithm is [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The accuracy of the ML model using KNN algorithm is 0.05
